### ISSUE TITLE
Android Crash on Killing the Application

### ISSUE THREAD

**Issue by raphire08** [khamidjon/gps_connectivity#1]
[android_background_crash.txt](https://github.com/khamidjon/gps_connectivity/files/11075955/android_background_crash.txt)
On killing android application, the code on android teardown tries to stop the GPS Listener and it causes error as argument passed is null. Listener was not started yet.

Please find the logs attached

```
at uz.thunder.gps_connectivity.GpsConnectivityBroadcastReceiver.onCancel(GpsConnectivityBroadcastReceiver.java:2)
at uz.thunder.gps_connectivity.GpsConnectivityPlugin.teardownChannels(GpsConnectivityPlugin.java:22)
[android_background_crash.txt](https://github.com/khamidjon/gps_connectivity/files/11075952/android_background_crash.txt)
at uz.thunder.gps_connectivity.GpsConnectivityPlugin.onDetachedFromEngine(GpsConnectivityPlugin.java:5)
```

**Comment by raphire08** [comment]
[android_background_crash.txt](https://github.com/khamidjon/gps_connectivity/files/11075969/android_background_crash.txt)
